import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUpRight, Check, ChevronRight, Clock3, Search, ShieldCheck, Sparkles, Store, Ticket, Users, X, RefreshCw, AlertCircle, MessageSquare, Copy } from 'lucide-react'
import './style.css'
const label = s => (s || '').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase())
const money = n => new Intl.NumberFormat('en-PH',{style:'currency',currency:'PHP',maximumFractionDigits:0}).format(n)
const neglected = t => !t.first_response_at && t.age_days > 7
const rank = t => ({urgent:4,high:3,medium:2,low:1}[t.priority]*1000 + t.age_days)
function App(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[branch,setBranch]=useState('all'),[view,setView]=useState('rescue'),[selected,setSelected]=useState(null),[assignee,setAssignee]=useState(''),[toast,setToast]=useState(''),[copied,setCopied]=useState(false)
 const [assignments,setAssignments]=useState(()=>{try{return JSON.parse(localStorage.getItem('suki-assignments')||'{}')}catch{return {}}})
 useEffect(()=>{fetch('/sandbox.json').then(r=>{if(!r.ok)throw Error('Could not load sandbox data');return r.json()}).then(setData).catch(e=>setError(e.message))},[])
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(id)},[toast])
 const tickets=useMemo(()=>data?[...data.tickets].sort((a,b)=>rank(b)-rank(a)):[],[data])
 const queue=tickets.filter(t=>(view==='all'||neglected(t))&&(branch==='all'||t.branch_code===branch)&&`${t.ticket_number} ${t.subject} ${t.branch_name} ${t.category}`.toLowerCase().includes(search.toLowerCase()))
 const rescue=tickets.filter(neglected), assignedCount=rescue.filter(t=>assignments[t.id]).length
 const csrs=data?.csrs.map(c=>({...c,workload:c.workload+Object.entries(assignments).filter(([id,s])=>s===c.id&&tickets.find(t=>t.id===Number(id))?.assigned_staff_id!==c.id).length-Object.entries(assignments).filter(([id,s])=>s!==c.id&&tickets.find(t=>t.id===Number(id))?.assigned_staff_id===c.id).length})).sort((a,b)=>a.workload-b.workload)||[]
 function open(t){setSelected(t);setAssignee(String(assignments[t.id]||t.assigned_staff_id||''));setCopied(false)}
 function assign(){if(!assignee)return;const next={...assignments,[selected.id]:Number(assignee)};try{localStorage.setItem('suki-assignments',JSON.stringify(next));setAssignments(next);setToast(`${selected.ticket_number} assigned in this browser`)}catch{setToast('Could not save. Browser storage is unavailable.')}}
 function prompt(t){return `Investigate Suki Mart ticket ${t.ticket_number} (ID ${t.id}) at ${t.branch_code}. Use the suki MCP server and sandbox time ${data.sandbox_now}. Check its order and delivery context, explain the priority, and recommend the next customer-care action. If the necessary tools are unavailable, tell me which tools need to be added.`}
 async function copyPrompt(){try{await navigator.clipboard.writeText(prompt(selected));setCopied(true)}catch{setToast('Clipboard unavailable. Select and copy the prompt below.')}}
 if(error)return <div className="loading"><AlertCircle/><h2>Unable to open the dashboard</h2><p>{error}</p><button onClick={()=>location.reload()}>Try again</button></div>
 if(!data)return <div className="loading"><Store size={36}/><h2>Opening Suki Mart…</h2><p>Getting your customer-care queue ready.</p></div>
 return <div className="shell">
 <aside className="sidebar"><a className="brand" href="/"><span className="logo"><Store size={23}/></span><span>suki<span className="brand-dot">.</span><small>MART OPERATIONS</small></span></a><div className="workspace"><span className="avatar">SM</span><div>Suki Mart<small>Metro Manila · 12 branches</small></div><ChevronRight size={15}/></div><div className="nav-label">WORKSPACE</div><button className={`nav ${view==='rescue'?'active':''}`} onClick={()=>setView('rescue')}><ShieldCheck size={19}/> Complaint rescue <span>{rescue.length}</span></button><button className={`nav ${view==='all'?'active':''}`} onClick={()=>setView('all')}><Ticket size={19}/> All unresolved <span>{tickets.length}</span></button><div className="sidebar-bottom"><div className="hermes-mark"><Sparkles size={19}/> Built for Hermes</div><p>From overlooked complaint<br/>to a clear next step.</p><div className="sandbox-pill"><span/> Sandbox workspace</div></div></aside>
 <main><header><div className="breadcrumb">Workspace <ChevronRight size={14}/> Customer experience</div><div className="header-right"><span className="snapshot"><span/> Data snapshot</span><span className="avatar small">OP</span></div></header><div className="content"><div className="page-top"><div><div className="eyebrow">CUSTOMER CARE, WITH A LITTLE MORE CARE</div><h1>{view==='rescue'?'No complaint left behind.':'Your customer-care inbox.'}</h1><p>{view==='rescue'?'Find forgotten conversations. Give every customer a next step.':'A single view of open and pending tickets across your branches.'}</p></div><span className="date"><Clock3 size={15}/> {new Date(data.sandbox_now.replace(" ","T")).toLocaleString("en-US",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit"})}<small>Sandbox time · Manila</small></span></div>
 <section className="metrics"><Metric icon={Ticket} title="Unresolved tickets" value={tickets.length} note="Across all 12 branches"/><Metric icon={Clock3} title="Needs a first response" value={rescue.length} note="Unanswered for more than 7 days" warning/><Metric icon={AlertCircle} title="High-priority rescues" value={rescue.filter(t=>['urgent','high'].includes(t.priority)).length} note="High or urgent priority"/><Metric icon={Users} title="Assigned in this demo" value={assignedCount} note="Saved on this browser"/></section>
 <section className="insight"><div className="insight-icon"><Sparkles size={22}/></div><div><div className="insight-title">A smaller queue. A bigger impact.</div><p>{rescue.length} customers have waited over a week without a first response. Start with urgent cases, review the facts, then give each ticket an owner.</p></div><span className="insight-tag">RESCUE BRIEF</span></section>
 <section className="queue"><div className="queue-top"><div><h2>{view==='rescue'?'The rescue queue':'Unresolved tickets'} <span>{queue.length}</span></h2><p>Ordered by priority, then longest wait. Select a ticket to investigate.</p></div><button className="text-button" onClick={()=>{setSearch('');setBranch('all')}}><RefreshCw size={14}/> Reset filters</button></div><div className="filters"><div className="search"><Search size={17}/><input aria-label="Search tickets" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search ticket, issue, or branch…"/>{search&&<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={15}/></button>}</div><select aria-label="Filter branch" value={branch} onChange={e=>setBranch(e.target.value)}><option value="all">All branches</option>{data.branches.map(b=><option key={b.id} value={b.code}>{b.code} · {b.name}</option>)}</select></div><div className="table-scroll"><table><thead><tr><th>CONVERSATION</th><th>BRANCH</th><th>PRIORITY</th><th>WAITING</th><th>OWNER</th><th/></tr></thead><tbody>{queue.map(t=><tr key={t.id} onClick={()=>open(t)}><td><button className="ticket-link" onClick={e=>{e.stopPropagation();open(t)}}>{t.subject}</button><div className="subline">{t.ticket_number}<span>·</span>{label(t.category)}</div></td><td><span className="branch-tag">{t.branch_code||'—'}</span></td><td><span className={`priority ${t.priority}`}><span/>{label(t.priority)}</span></td><td><span className={neglected(t)?'wait':''}>{Math.floor(t.age_days)} days</span><div className="subline">{t.first_response_at?'Response recorded':'No first response'}</div></td><td>{assignments[t.id]?<span className="owner"><Check size={13}/>{data.csrs.find(c=>c.id===assignments[t.id])?.name||'Assigned'}</span>:t.assigned_staff_id?<span className="owner">{data.csrs.find(c=>c.id===t.assigned_staff_id)?.name||'Assigned CSR'}</span>:<span className="unassigned">Unassigned</span>}</td><td><ArrowUpRight size={17}/></td></tr>)}</tbody></table>{queue.length===0&&<div className="empty"><Search size={28}/><h3>No matching tickets</h3><p>Try a different search or branch.</p><button onClick={()=>{setSearch('');setBranch('all')}}>Clear filters</button></div>}</div><div className="table-footer"><span>{queue.length} conversations · {view==='rescue'?'First response overdue':'Open & pending'}</span><span>Source: Suki Mart sandbox</span></div></section><footer>Made for the moments that matter.<span>Suki Mart · CAMP / RUN 2026</span></footer></div></main>
 {selected&&<div className="overlay" onClick={()=>setSelected(null)}><section className="drawer" role="dialog" aria-modal="true" aria-labelledby="ticket-title" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setSelected(null)}}><div className="drawer-top"><span>{selected.ticket_number} · {selected.branch_code}</span><button autoFocus aria-label="Close ticket details" onClick={()=>setSelected(null)}><X size={21}/></button></div><span className={`priority ${selected.priority}`}><span/>{label(selected.priority)}</span><h2 id="ticket-title">{selected.subject}</h2><div className="detail-meta">{label(selected.category)} · {label(selected.status)} · {Math.floor(selected.age_days)} days waiting</div><div className="detail-block"><h3><MessageSquare size={16}/> Customer’s message</h3><p>{selected.description}</p><small>Opened {selected.created_at} · Manila</small></div><div className="detail-block"><h3>Order & delivery context</h3>{selected.order_created_at > selected.created_at && <p className="context-warning">The linked order is dated after this ticket. Verify this relationship before acting.</p>}{selected.order_number?<><div className="fact"><span>Order</span><strong>{selected.order_number}</strong></div><div className="fact"><span>Total</span><strong>{money(selected.order_total)}</strong></div><div className="fact"><span>Status</span><strong>{label(selected.order_status)}</strong></div><div className="fact"><span>Delivery</span><strong>{label(selected.delivery_status)||'Not linked'}</strong></div>{selected.promised_by&&<div className="fact"><span>Promised by</span><strong>{selected.promised_by}</strong></div>}{selected.failure_reason&&<p>{selected.failure_reason}</p>}</>:<p className="muted">No order is linked to this ticket. Verify the details with the customer before recommending a remedy.</p>}</div><div className="detail-block"><h3><Users size={16}/> Give this ticket an owner</h3><label className="field-label" htmlFor="csr">Customer service representative</label><select id="csr" value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Choose a CSR</option>{csrs.map(c=><option key={c.id} value={c.id}>{c.name} · {c.workload} active tickets</option>)}</select><button className="primary" disabled={!assignee} onClick={assign}><Check size={16}/> Save demo assignment</button><p className="fine">Demo assignments stay in this browser. They do not update the sandbox database.</p></div><div className="hermes-box"><h3><Sparkles size={17}/> Investigate with Hermes</h3><p>Copy this ticket’s context into Hermes to start an investigation.</p><textarea readOnly aria-label="Hermes investigation prompt" value={prompt(selected)}/><button className="secondary" onClick={copyPrompt}><Copy size={15}/>{copied?'Copied to clipboard':'Copy Hermes prompt'}</button></div></section></div>}{toast&&<div className="toast" role="status"><Check size={17}/>{toast}</div>}
 </div>
}
function Metric({icon:Icon,title,value,note,warning}){return <article className={`metric ${warning?'metric-warning':''}`}><div className="metric-title">{title}<Icon size={17}/></div><div className="metric-value">{value}<span>{warning?'need attention':''}</span></div><p>{note}</p></article>}
createRoot(document.getElementById('root')).render(<App/> )
